### ISSUE TITLE
How use Frei0r effects?

### ISSUE THREAD

**Issue by coldev** [IljaKosynkin/FFmpeg-Development-Kit#1]
How use Frei0r effects in android ?  one example ffplay and ffmepg

thanks

**Comment by IljaKosynkin** [comment]
@coldev AFAIK, Frei0r is separate library that must be linked in FFmpeg building process. This Kit is is just for building vanilla FFmpeg without any additional libs as it might affect licensing. It's possible in future that I will create branch with example of integration of such lib (like libx264 as I've done it some time ago), however I can't make any promises on that part. 
Sorry for the late response!
