### ISSUE TITLE
Is PROJECT path correct?

### ISSUE THREAD

**Issue by Dinu8** [IljaKosynkin/FFmpeg-Development-Kit#14]
Hi and thank you for sharing this great project!
Is PROJECT path correct in line 12?
https://github.com/IljaKosynkin/FFmpeg-Development-Kit/blob/master/ffmpeg/build.sh#L12
PROJECT="$(dirname "${NDK}")/JNI/app"

Shouldn't this line be:
PROJECT="$(dirname "${DIR}")/JNI/app"

**Comment by IljaKosynkin** [comment]
@Dinu8 
JNI project is supposed to be in the same folder NDK is located. Like:
Kit:
    NDK
    JNI
And this line is doing exactly that. You're free to put any other suitable path to the "app" folder of your project in there, I just find it to be more convenient to have everything in one place (or close enough to each other).

**Comment by Dinu8** [comment]
Yes, I missed that JNI should be placed in the same folder as NDK.
