### ISSUE TITLE
Where do i find build.sh file?

### ISSUE THREAD

**Issue by samyakjain** [IljaKosynkin/FFmpeg-Development-Kit#15]
I have cloned ffmpeg for macos and copy pasted in source directory under ndk folder but i am not able to find build.sh file.

**Comment by caiomcg** [comment]
The build.sh file is provided along with the FFMPEG inside of this repo. You can locate it at: FFmpeg-Development-Kit/ffmpeg/build.sh

**Comment by anonym24** [comment]
@samyakjain Are you serious? https://github.com/IljaKosynkin/FFmpeg-Development-Kit/blob/master/ffmpeg/build.sh
