### ISSUE TITLE
Clang is unable to create executable file

### ISSUE THREAD

**Issue by msroid** [IljaKosynkin/FFmpeg-Development-Kit#18]
Hi,
I tried several times as your instructions to compile ffmpeg but every time I got this error:
```
cp: cannot stat '/home/majid/A/JNI/app/libs/armeabi-v7a': No such file or directory
/home/majid/A/NDK/toolchains/llvm/prebuilt/linux-x86_64/bin/clang is unable to create an executable file.
C compiler test failed.
```
in ffmpeg folder in build.sh file in this line:
`HOST="darwin-x86_64"`
there is no such a folder in ndk and I replaced it by:
`HOST="linux-x86_64"`
which exists in ndk.
This is only change that I did to those files and folders.
and when it finishes its work prints these messages:

> 
> cp: cannot create regular file 'android/arm64-v8a/Android.mk': No such file or directory
> Android NDK: /home/majid/A/JNI/app/jni/Android.mk: Cannot find module with tag 'ffmpeg/android/arm64-v8a' in import path    
> Android NDK: Are you sure your NDK_MODULE_PATH variable is properly defined ?    
> Android NDK: The following directories were searched:    
> Android NDK:         
> /home/majid/A/JNI/app/jni/Android.mk:11: *** Android NDK: Aborting.    .  Stop.
> cp: cannot stat '/home/majid/A/JNI/app/libs/arm64-v8a': No such file or directory
> 
Please help me! I've been dealing with this all past two weeks!

**Comment by msroid** [comment]
At the end I have an android folder which contains only another folder(armeabi-v7a)

**Comment by anonym24** [comment]
for me it builds .so files even if it shows this error:

```
Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin/clang is unable to create an executable file.
C compiler test failed.

```
![screenshot from 2018-12-16 17-58-33](https://user-images.githubusercontent.com/8851301/50055802-418eb000-015c-11e9-898a-e5ccc0eea523.png)

![screenshot from 2018-12-16 17-59-14](https://user-images.githubusercontent.com/8851301/50055809-52d7bc80-015c-11e9-91f1-78a1b292b650.png)

And you have to tell us more. Where did you put ffmpeg folder? it should be in `ndk-bundle/sources`, e.g. :`/home/user/Android/Sdk/ndk-bundle/sources/ffmpeg/`

`DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PARENT="$(dirname "${DIR}")"
NDK="$(dirname "${PARENT}")"
PROJECT="$(dirname "${NDK}")/JNI/app"
PROJECT_JNI="$PROJECT/jni"
PROJECT_LIBS="$PROJECT/libs"
SYSROOT="$NDK/sysroot"
HOST="linux-x86_64"
LLVM_TOOLCHAIN="$NDK/toolchains/llvm/prebuilt/$HOST/bin"
IS_CLANG=1

CFLAGS="-O3 -fPIC"
LDFLAGS="-lc"

build () {
    ARCH=$1
    LEVEL=$2
    CONFIGURATION="--enable-cross-compile --disable-static --disable-programs --disable-doc --disable-htmlpages --disable-manpages --disable-podpages --disable-txtpages --enable-shared --disable-protocols --enable-protocol=file --enable-pic --disable-hwaccels --disable-parsers --disable-bsfs --disable-indevs --disable-outdevs --disable-devices --disable-filters --disable-network $3"
    LIB_FOLDER="lib"

    case $ARCH in
        "armeabi-v7a")
            TARGET="arm-linux-androideabi"

            if [ $IS_CLANG = 1 ]; then
                CC_FLAGS="-target thumbv7-none-linux-androideabi -mfpu=vfpv3-d16 -mfloat-abi=soft"
            else
                CC_FLAGS="-mfpu=vfpv3-d16 -mfloat-abi=soft"
            fi

            LDFLAGS="--fix-cortex-a8 $LDFLAGS"
            PLATFORM_ARCH="arm"
            TOOLCHAIN_FOLDER=$TARGET
        ;;
        "arm64-v8a")
            TARGET="aarch64-linux-android"

            if [ $IS_CLANG = 1 ]; then
                CC_FLAGS="-target aarch64-none-linux-android -mfpu=neon -mfloat-abi=soft"
            else
                CC_FLAGS=""
            fi

            PLATFORM_ARCH="arm64"
            CONFIGURATION="$CONFIGURATION --disable-pthreads"
            TOOLCHAIN_FOLDER=$TARGET
        ;;
        "x86")
            TARGET="i686-linux-android"

            if [ $IS_CLANG = 1 ]; then
                CC_FLAGS="-target i686-none-linux-androideabi -mtune=intel -mssse3 -mfpmath=sse -m32"
            else
                CC_FLAGS="-mtune=intel -mssse3 -mfpmath=sse -m32"
            fi

            PLATFORM_ARCH="x86"
            TOOLCHAIN_FOLDER=$PLATFORM_ARCH
        ;;
        "x86_64")
            TARGET="x86_64-linux-android"

            if [ $IS_CLANG = 1 ]; then
                CC_FLAGS="-target x86_64-none-linux-androideabi -msse4.2 -mpopcnt -m64 -mtune=intel"
            else
                CC_FLAGS="-msse4.2 -mpopcnt -m64 -mtune=intel"
            fi

            PLATFORM_ARCH="x86_64"
            LIB_FOLDER="lib64"
            TOOLCHAIN_FOLDER=$PLATFORM_ARCH
        ;;
    esac

    TOOLCHAIN=$NDK/toolchains/$TOOLCHAIN_FOLDER-4.9/prebuilt/$HOST/bin

    CC=$LLVM_TOOLCHAIN/clang
    CXX=$LLVM_TOOLCHAIN/clang++
    AS=$CC

    AR=$TOOLCHAIN/$TARGET-ar
    LD=$TOOLCHAIN/$TARGET-ld
    STRIP=$TOOLCHAIN/$TARGET-strip

    PREFIX="android/$ARCH"

    ./configure --prefix=$PREFIX  \
                $CONFIGURATION \
                --ar=$AR --strip=$STRIP --ld=$LD --cc=$CC --cxx=$CXX --as=$AS \
                --target-os=android \
                --extra-cflags="$CC_FLAGS -I$SYSROOT/usr/include/$TARGET $CFLAGS" \
                --extra-ldflags="-L$NDK/platforms/android-$LEVEL/arch-$PLATFORM_ARCH/usr/$LIB_FOLDER $LDFLAGS" \
                --sysroot=$SYSROOT --extra-libs=-lgcc

    $NDK/prebuilt/$HOST/bin/make clean
    $NDK/prebuilt/$HOST/bin/make -j4
    $NDK/prebuilt/$HOST/bin/make install
}

build "armeabi-v7a" "19" "--disable-asm"
#build "arm64-v8a" "21" "--disable-asm"
#build "x86_64" "21" "--disable-asm"
#build "x86" "19"`

you can also add next to your `.bashrc` file (`gedit ~/.bashrc`)

`export NDK=/home/user/Android/Sdk/ndk-bundle
export PATH=$PATH:$NDK
export PATH=$PATH:/home/user/Android/Sdk
export ANDROID_NDK=/home/user/Android/Sdk/ndk-bundle
export PATH=$PATH:$ANDROID_NDK
export ANDROID_SDK=/home/user/Android/Sdk
export PATH=$PATH:$ANDROID_SDK`

**Comment by anonym24** [comment]
I edited script a little bit (removed gcc related lines), it doesn't print errors like `clang is unable to create an executable file.
C compiler test failed.`

```
#FFmpeg - 4.0.2 build as LPGL without x264 lib

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PARENT="$(dirname "${DIR}")"
NDK="$(dirname "${PARENT}")"
PROJECT="$(dirname "${NDK}")/JNI/app"
PROJECT_JNI="$PROJECT/jni"
PROJECT_LIBS="$PROJECT/libs"
SYSROOT="$NDK/sysroot"
HOST="linux-x86_64"
LLVM_TOOLCHAIN="$NDK/toolchains/llvm/prebuilt/$HOST/bin"

CFLAGS="-O3 -fPIC"
LDFLAGS="-lc"

build () {
    ARCH=$1
    LEVEL=$2
    #CONFIGURATION="--disable-asm --enable-cross-compile --disable-static --disable-programs --disable-doc --enable-shared --enable-protocol=file --enable-pic --enable-small $3"
    CONFIGURATION="--enable-cross-compile --disable-static --disable-programs --disable-doc --disable-htmlpages --disable-manpages --disable-podpages --disable-txtpages --enable-shared --disable-protocols --enable-protocol=file --enable-pic --disable-hwaccels --disable-parsers --disable-bsfs --disable-indevs --disable-outdevs --disable-devices --disable-filters --disable-network $3"
    LIB_FOLDER="lib"

    case $ARCH in
        "armeabi-v7a")
            TARGET="arm-linux-androideabi"
            CC_FLAGS="-target thumbv7-none-linux-androideabi -mfpu=vfpv3-d16 -mfloat-abi=soft"
            LDFLAGS="--fix-cortex-a8 $LDFLAGS"
            PLATFORM_ARCH="arm"
            TOOLCHAIN_FOLDER=$TARGET
        ;;
        "arm64-v8a")
            TARGET="aarch64-linux-android"
            CC_FLAGS="-target aarch64-none-linux-android -mfpu=neon -mfloat-abi=soft"
            PLATFORM_ARCH="arm64"
            TOOLCHAIN_FOLDER=$TARGET
        ;;
        "x86")
            TARGET="i686-linux-android"
	    CC_FLAGS="-target i686-none-linux-androideabi -mtune=intel -mssse3 -mfpmath=sse -m32"
            PLATFORM_ARCH="x86"
            TOOLCHAIN_FOLDER=$PLATFORM_ARCH
        ;;
        "x86_64")
            TARGET="x86_64-linux-android"
            CC_FLAGS="-target x86_64-none-linux-androideabi -msse4.2 -mpopcnt -m64 -mtune=intel"
            PLATFORM_ARCH="x86_64"
            LIB_FOLDER="lib64"
            TOOLCHAIN_FOLDER=$PLATFORM_ARCH
        ;;
    esac

    TOOLCHAIN=$NDK/toolchains/$TOOLCHAIN_FOLDER-4.9/prebuilt/$HOST/bin

    CC=$LLVM_TOOLCHAIN/clang
    CXX=$LLVM_TOOLCHAIN/clang++
    AS=$CC

    AR=$TOOLCHAIN/$TARGET-ar
    LD=$TOOLCHAIN/$TARGET-ld
    STRIP=$TOOLCHAIN/$TARGET-strip

    PREFIX="android/$ARCH"

./configure --prefix=$PREFIX \
$CONFIGURATION \
--ar=$AR --strip=$STRIP --ld=$LD --cc=$CC --cxx=$CXX --as=$AS \
--target-os=android \
--extra-cflags="$CC_FLAGS -I$SYSROOT/usr/include/$TARGET $CFLAGS" \
--extra-ldflags="-L$NDK/toolchains/$TOOLCHAIN_FOLDER-4.9/prebuilt/$HOST/lib/gcc/$TARGET/4.9.x -L$NDK/platforms/android-$LEVEL/arch-$PLATFORM_ARCH/usr/lib $LDFLAGS" \
--sysroot=$SYSROOT --extra-libs=-lgcc

    $NDK/prebuilt/$HOST/bin/make clean
    $NDK/prebuilt/$HOST/bin/make -j4
    $NDK/prebuilt/$HOST/bin/make install
}

build "armeabi-v7a" "19" "--disable-asm"
#build "arm64-v8a" "21" "--disable-asm --disable-pthreads"
#build "x86_64" "21" "--disable-asm"
#build "x86" "19"
```

**Comment by anonym24** [comment]
Also I found why it can print such error

It happens when you don't have `-L$NDK/toolchains/$TOOLCHAIN_FOLDER-4.9/prebuilt/$HOST/lib/gcc/$TARGET/4.9.x` in `--extra-ldflags` 

Though it still works. It builds .so files despite showing this error:

`--extra-ldflags="-L$NDK/platforms/android-$LEVEL/arch-$PLATFORM_ARCH/usr/lib $LDFLAGS" `

@IljaKosynkin what do you think?

mb it's only for some tests 

`/home/user/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin/clang is unable to create an executable file.
C compiler test failed.
`
or you need it only once, but for the next builds using the same FFmpeg folder you can remove it

**Comment by anonym24** [comment]
Got it. Actually `-L$NDK/toolchains/$TOOLCHAIN_FOLDER-4.9/prebuilt/$HOST/lib/gcc/$TARGET/4.9.x` is of course necessary 

without this line it just will build the last successful configuration when `-L$NDK/toolchains/$TOOLCHAIN_FOLDER-4.9/prebuilt/$HOST/lib/gcc/$TARGET/4.9.x` was set in the script file

**Comment by anonym24** [comment]
Yes I also have issue with x86-64 https://github.com/IljaKosynkin/FFmpeg-Development-Kit/issues/21

**Comment by anonym24** [comment]
This issue for x86_64 was fixed https://github.com/IljaKosynkin/FFmpeg-Development-Kit/commit/ad9bcb6821d8f20789878f2340ac88a74e877c02#diff-7ddcec9a2b20f9f3cd2cbccb9c733aefR126

redownload build.sh file

**Comment by msroid** [comment]
I replaced the updated build.sh file with the previous one but the result is the same!
The build for armebi-v7a is done but there is no folder for arm64-v8 in the android folder and at the end it shows this messages:

> > cp: cannot create regular file 'android/arm64-v8a/Android.mk': No such file or directory
> Android NDK: /home/majid/A/JNI/app/jni/Android.mk: Cannot find module with tag 'ffmpeg/android/arm64-v8a' in import path    
> Android NDK: Are you sure your NDK_MODULE_PATH variable is properly defined ?    
> Android NDK: The following directories were searched:    
> Android NDK:         
> /home/majid/A/JNI/app/jni/Android.mk:11: *** Android NDK: Aborting.    .  Stop.
> cp: cannot stat '/home/majid/A/JNI/app/libs/arm64-v8a': No such file or directory

I have a folder (A) in /home/majid/ directory. and it contains JNI and NDK folders and I also put the ffmpeg folder here: /home/majid/A/NDK/sources/ffmpeg

**Comment by anonym24** [comment]
Redownload the whole git, you can also use my tiny build script from https://github.com/IljaKosynkin/FFmpeg-Development-Kit/issues/21

**Comment by msroid** [comment]
Thanks for you help you are my savior :)
Just something to mention, when I run build.sh file for all architectures it didn't work for arm-v8a but when I ran it just for this one it worked!
