### ISSUE TITLE
Is using ffmpeg.c illegal for closed-source app?

### ISSUE THREAD

**Issue by anonym24** [IljaKosynkin/FFmpeg-Development-Kit#19]
https://github.com/IljaKosynkin/FFmpeg-Development-Kit/blob/master/JNI/app/jni/ffmpeg.c

I recompiled FFmpeg excluding x264 (LGPL), but I still want to use FFmpeg command lines (it needs ffmpeg.c source file and some others)

**Comment by IljaKosynkin** [comment]
Hey!
Sorry for late response!
In case you still need my answer: I'm pretty sure it's not illegal as long as you mention clearly that you use FFmpeg according to their license. 
But I'm not a lawyer, so if you really want to be safe - I would suggest checking it with one.
Closing issue for now!
