### ISSUE TITLE
Two-Pass with libx264 

### ISSUE THREAD

**Issue by msroid** [IljaKosynkin/FFmpeg-Development-Kit#22]
According to documentation for using this method we have to run ffmpeg twice like this:

Example:
`
```
ffmpeg -y -i input -c:v libx264 -b:v 2600k -pass 1 -an -f mp4 /dev/null && \

ffmpeg -i input -c:v libx264 -b:v 2600k -pass 2 -c:a aac -b:a 128k output.mp4
```
`

but I don't know how to run ffmpeg twice in android!

**Comment by IljaKosynkin** [comment]
Hey!
Sorry for very late response!
I think you need to execute native method twice then, at least it seems like this.
Note that previous versions didn't had libx264 included, you can check out latest version which has it.
Closing issue for now, feel free to re-open if needed!
