### ISSUE TITLE
FFmpeg 4 - doesn't work on KitKat (19 API). Befor v3.2.* FFmpeg was working ok. Cannot locate symbol "mmap64"

### ISSUE THREAD

**Issue by anonym24** [IljaKosynkin/FFmpeg-Development-Kit#23]
`failed: dlopen failed: cannot locate symbol "mmap64" referenced by "libavutil.so"...`

**Comment by IljaKosynkin** [comment]
Hey!
Sorry for late response, had no time to take care of repo for past few years!
Check out latest version and let me know if it helps!
Closing issue for now, feel free to re-open!
