### ISSUE TITLE
./build.sh execution not generate libvideokit.so inside JNI/app/out folder

### ISSUE THREAD

**Issue by kohiyadav** [IljaKosynkin/FFmpeg-Development-Kit#26]
build.sh file having one entry like : PROJECT_LIBS="$PROJECT/libs"
Do we need to specify that folder libs inside JNI/app/ .
If yes then  what would be the value inside it as one more entry in build.sh file is like 
yes | cp -rf "$PROJECT_LIBS/$ARCH" "$PROJECT/out/$ARCH"

it looks like copy the entry from libs/arch to out/arch.

Right now I have just downloaded the JNI and put it with NDK and run ./build.sh on ffmpeg directory location then it only generate android folder with architecture inside the sources/ffmpeg/android but nothing is generated in JNI/app/out folder

Please help

**Comment by IljaKosynkin** [comment]
Hey!
Sorry for late response, had no time to really look after the repo.
You can check out latest version which has CMake integration and overall better then my previous works.
I'm closing the issue for now, fell free to re-open if you still need help!
