### ISSUE TITLE
Cmake  generate error at windows 

### ISSUE THREAD

**Issue by CMingTseng** [IljaKosynkin/FFmpeg-Development-Kit#29]
Dear  Sir

i use windows 

as this 

https://stackoverflow.com/questions/28070810/cmake-generate-error-on-windows-as-it-uses-as-escape-seq

PATH=${ANDROID_TOOLCHAIN_ROOT}/bin:$ENV{PATH}

when build the project 

the  .cxx folder will gen ***.cmake files 

i get  D:\SDK  not Cmake use D:/SDK

THX

**Comment by IljaKosynkin** [comment]
Windows is not supported as host platform. I would recommend trying out some Linux distribution. Alternatively, Cygwin might help, but I never have done this.

**Comment by IljaKosynkin** [comment]
Discussed elsewhere, closing.
