### ISSUE TITLE
Not compiling in Linux mint 18.3

### ISSUE THREAD

**Issue by duindain** [IljaKosynkin/FFmpeg-Development-Kit#3]
Hi,
Thanks for making the library, I'm trying to compile ffprobe and ffmpeg for various android platforms for release with an app

- I've downloaded the repo
- Installed yasm
- Downloaded and extracted NDK r14b
- Extracted the repo to the sources dir
- Added an env variable for NDK to point to r14b root dir
- I've copied the included JNI folder to multiple places, root of NDK
- One level above NDK (I ended up deleting this one but it gets recreated by the scripts)

Running ./build_all.sh > output.txt so i can see the entire output shows 

`doc/Makefile:152: recipe for target 'install-man' failed
Android NDK: Your APP_BUILD_SCRIPT points to an unknown file: /home/myusername/Software/android-ndk-r14b/jni/Android.mk`

The file doesn't exist at that location i do see Android.mk in the NDK/JNI/app/jni directory

There seems to be a bit of confusion in the scripts between cases sometimes looking for JNI othertimes jni which would fail in linux

Is there any steps missing? or something to try next i suspect I'm missing something that isn't in the readme?

**Comment by IljaKosynkin** [comment]
@duindain Hello.
Can you please try on recent master in case you still need libs? I updated repo to support FFmpeg 4.0 and Clang. I suspect PRJECT_HOME variable may be messed up and it is set up directly in the script now to avoid problems. 
Sorry for the late response!
