### ISSUE TITLE
Access denied on windows

### ISSUE THREAD

**Issue by CMingTseng** [IljaKosynkin/FFmpeg-Development-Kit#30]
Dear Sir

I  try ref this post :  https://github.com/IljaKosynkin/FFmpeg-Development-Kit/issues/29 to fix

and then i can start build

but when  step [5/17] Performing configure step for 'ffmpeg_target' 

i get error  "FAILED: ffmpeg_pref/src/ffmpeg_target-stamp/ffmpeg_target-configure "

i google the error  maybe like this post   https://github.com/ninja-build/ninja/issues/1646

THX

**Comment by IljaKosynkin** [comment]
Windows is not supported as host platform. I would recommend trying out some Linux distribution. Alternatively, Cygwin might help, but I never have done this.

**Comment by CMingTseng** [comment]
> Windows is not supported as host platform. I would recommend trying out some Linux distribution. Alternatively, Cygwin might help, but I never have done this.

OK   thx  Sir

i  fork and pull request

can help me ?

THX
____________________


Dear Sir

very thx your project 

i    modify  something


1.  add ndkVersion "XXX" to set define NDK version   https://developer.android.com/studio/projects/install-ndk#apply-specific-version

2. at normal develop we like pure project  like :  app-project +library-project  .so i try to export the  VideoKit as standalone

library  project  and it work  --- 6af1a9ffe71d4b1116afacaf73124fdad2ddc462 

below  is fail   can fix it ?  or teach me ?

3. before your project  .we normal use shell script  @ linux/osx  to build ffmpeg to get  all ffmpeg library so file ( libavutil /libswresample/libavcodec/ibavformat/libswscale/libavfilter/ libavdevice)  . so  i try to export pure ffmpeg as standalone

library  project . for my understand the project ffmpeg dependencies libx264 to support x264  future ?

so i try export those 

pure x264 library  --  969330afe3f1d0426bd1d3098bbfb7a832b7480f

and then 

the  native-lib ( VideoKit ) dependencies  ffmpeg (libavutil /libswresample/libavcodec/ibavformat/libswscale/libavfilter/ libavdevice ) 

so next export  

pure x264 library +pure ffmpeg library + native-lib library  --  04298aa074424c475db29868a506a1ee335a01d6

THX

**Comment by IljaKosynkin** [comment]
Can't really help you with Cygwin, never used it. I suggest installing some linux distro either as dual-boot on your Windows machine or into some VM. As far as I remember, I did verify that DK built and sample ran correctly under Ubuntu in VM.

**Comment by IljaKosynkin** [comment]
Discussed elsewhere, closing.
