### ISSUE TITLE
 reserved or not valid for certain CMake features

### ISSUE THREAD

**Issue by CMingTseng** [IljaKosynkin/FFmpeg-Development-Kit#32]
Dear Sir

sorry for my poor English

i  try  export   build pure ffmpeg as module project  (  at  Mac OSX  10.5   not windows )

i get error

PS.  about   PR &  issue  i will re-write reason   sorry for  my poor englisg can not full expression

`Execution failed for task ':library_ffmpeg:generateJsonModelFreeDebug'.
> ...\CMakeLists.txt : C/C++ freeDebug|armeabi-v7a : CMake Error at ..CMakeLists.txt:188 (add_library):
    The target name
    "..cmdutils.c"
    is reserved or not valid for certain CMake features, such as generator
    expressions, and may result in undefined behavior.`

**Comment by IljaKosynkin** [comment]
Discussed elsewhere, closing.
