### ISSUE TITLE
log progress in txt file

### ISSUE THREAD

**Issue by pavel-corsaghin** [IljaKosynkin/FFmpeg-Development-Kit#4]
Hi, Sorry for bothering you again, can you show me how to save the log to the .txt file?

**Comment by IljaKosynkin** [comment]
@pavel-corsaghin 
Hello. Probably you can redirect logical to the file as described here: 
[SO](https://stackoverflow.com/questions/19565685/saving-logcat-to-a-text-file-in-android-device/37541596)
I'm closing issue now, please open new one in case something still wrong. 
Sorry for the late response!
