### ISSUE TITLE
Possibly no need to remove strtod.o in the build script

### ISSUE THREAD

**Issue by dturner** [IljaKosynkin/FFmpeg-Development-Kit#5]
I ran into the same issue as you when compiling for arm64.

`libavutil/../compat/strtod.o: error adding symbols: File in wrong format`

However, after running `make clean` the error went away (because strtod.o is then compiled for the correct architecture). You have `make clean` in your build script so `rm -f $(pwd)/compat/strtod.o` shouldn't be required. Just thought you should know.

**Comment by IljaKosynkin** [comment]
@dturner removed in update to FFmpeg 4.0. Thanks for the contribution!
