### ISSUE TITLE
I don't see any processing logs

### ISSUE THREAD

**Issue by anonym24** [IljaKosynkin/FFmpeg-Development-Kit#6]
```
// If loglevel greater then 0 there will VERY BIG AND ANNOYING LOG of ffmpeg working process
    // that however could be very useful in case return code didn't help a lot
    private native int run(int loglevel, String[] args);

```

all I see is (when setting `videoKit.setLogLevel(LogLevel.FULL);`):

```
    Option: /storage/emulated/0/test5.mkv
    Option: -y
    Option: -map
    Option: 0:s:2
    Option: -strict
    Option: -2
    Option: /storage/emulated/0/test5.mkvsubs.srt
```

but it's just my parameters which I already know

**Comment by inventionsbyhamid** [comment]
Have you been able to figure out how to enable logging? @anonym24 

Edit:
I enabled logs by changing int loglevel = 0 to int loglevel = 2 in ffmpeg.c inside app/jni

**Comment by IljaKosynkin** [comment]
@anonym24 @inventionsbyhamid 
you should be able to pass log level parameter via JNI from Java code, however setting parameter directly in the C code will work too.
Close this issue as resolved.
