### ISSUE TITLE
Please update to FFmpeg 4.0

### ISSUE THREAD

**Issue by anonym24** [IljaKosynkin/FFmpeg-Development-Kit#7]

**Comment by anonym24** [comment]
I already found and edited scripts for building FFMpeg 4.0 using NDK 15 (to build as LGPL without additional libs/codecs, e.g. like x264) https://github.com/bytedeco/javacpp-presets/issues/562

but I'm not sure how to build videokit lib (and what would be better for ndk-build or cmake)

**Comment by IljaKosynkin** [comment]
@anonym24 updated to FFmpeg 4.0 on master. Sorry for the delay.
